language: java
sudo: false

 cache:
  directories:
  - "$HOME/.m2"

before_script: echo 'spring-cloud-scaffold'

jobs:
  include:
  - stage: test
    jdk: oraclejdk8
    script: 
    - cd ./springcloud-jpa
    - mvn clean verify -DskipTests=true
  - jdk: oraclejdk8
    script: 
    - cd ./springcloud-mybatisplus
    - mvn clean verify -DskipTests=true