language: java
sudo: false

cache:
  directories:
  - "$HOME/.m2"

jobs:
  include:
  - stage: test
    jdk: oraclejdk8
    script: mvn clean test

branches:
  only:
  - master

after_success:
  - codecov